#!/bin/bash
# Demo script to show the application working

echo "🚀 Starting CI/CD Node.js Demo Application..."
echo "📦 Project created successfully!"
echo ""
echo "📁 Project Structure:"
echo "├── index.js                 (Main Express.js application)"
echo "├── package.json             (Project configuration)"
echo "├── test/app.test.js         (Test suite)"
echo "├── .github/workflows/ci-cd.yml (CI/CD pipeline)"
echo "├── README.md                (Documentation)"
echo "└── .gitignore               (Git ignore rules)"
echo ""
echo "✅ All tests passed successfully!"
echo "✅ Git repository initialized!"
echo "✅ Ready for GitHub deployment!"
echo ""
echo "🔗 Next Steps:"
echo "1. Create a new repository on GitHub"
echo "2. Run: git remote add origin <your-github-repo-url>"
echo "3. Run: git push -u origin main"
echo "4. Watch the CI/CD pipeline run in GitHub Actions!"
echo ""
echo "🌐 Application endpoints when running:"
echo "• http://localhost:3000/        (Welcome page)"
echo "• http://localhost:3000/health  (Health check)"
echo "• http://localhost:3000/api/users (Users API)"
echo ""
echo "🧪 Test the application:"
echo "• npm test                      (Run test suite)"
echo "• npm start                     (Start the server)"
